sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t damodarag/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true damodarag/react-test npm test

after_success:
  - docker build -t damodarag/multi-client ./client
  - docker build -t damodarag/multi-nginx ./nginx
  - docker build -t damodarag/multi-server ./server
  - docker build -t damodarag/multi-worker ./worker
  # Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  # Take those images and push them to docker hub
  - docker push damodarag/multi-client
  - docker push damodarag/multi-nginx
  - docker push damodarag/multi-server
  - docker push damodarag/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker-test"
  env: "Multidockertest-env"
  bucket_name: "elasticbeanstalk-us-east-2-889401540119"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
